### ISSUE TITLE
Missing Close 'X' in alert boxes, causing weird padding issues for added Close 'X'

### ISSUE THREAD

**Issue by Alondite00** [ExactTarget/fuelux-mctheme#148]
I think bootstrap/mc styles are overwriting where the alert box close 'X' is supposed to be or it's not being accounted for.  @interactivellama and I came across the alert boxes missing the Close 'X' here: 

![image](https://cloud.githubusercontent.com/assets/10403596/6044666/d678382e-ac62-11e4-8a85-47958550b4cb.png)

I'm using the alert boxes here in Styleguide, but the styling/padding does not match up to what they're supposed to be from the .pdf copy.  Here's what they look like in styleguide without any hard resets:

![image](https://cloud.githubusercontent.com/assets/10403596/6044726/31edfefa-ac63-11e4-91a7-2a1aa8d063b8.png)

And here's what it's supposed to look like:

![image](https://cloud.githubusercontent.com/assets/10403596/6044803/cfd71da4-ac63-11e4-939d-85a41fab752a.png)

I did some hard css resetting to make it correct.  

```css
.alert {
     padding: 4px 8px 4px 32px;
}

.alert:before {
     top: 3px;
}

button.close {
     padding: 0;
     margin-top: -3px;
}

.close {
     line-height: 1;
}

```
