### ISSUE TITLE
Tree folder vertical alignment off in Firefox for selectable folder style

### ISSUE THREAD

**Issue by chriscorwin** [ExactTarget/fuelux-mctheme#191]
![screenshot 2015-03-10 13 39 34](https://cloud.githubusercontent.com/assets/362417/6581083/ffba41a4-c72a-11e4-844e-3c1afda6ad72.png)

**Comment by swilliamset** [comment]
Check the markup. Is the chevron inside the button? Firefox appears to be more sensitive to the placement.

**Comment by chriscorwin** [comment]
```
<div class="tree-branch-header">
    <button class="glyphicon icon-caret glyphicon-play"><span class="sr-only">Open</span></button>
    <button class="tree-branch-name">
        <span class="glyphicon icon-folder glyphicon-folder-close"></span>
        <span id="folder1-label" class="tree-label">Ascending and Descending</span>
    </button>
</div>
```

**Comment by swilliamset** [comment]
i believe moving the `.icon-caret` into the `button` and making it a `span` will do the trick

**Comment by interactivellama** [comment]
The event fires on the click of the `<button>`. I think this would cause a event bubble up.

**Comment by swilliamset** [comment]
yep that's why we change it to a span so just one button

**Comment by cormacmccarthy** [comment]
![image](https://cloud.githubusercontent.com/assets/8006971/6674366/74c8402c-cbef-11e4-9757-d6c0e00cefae.png)

http://fuelux-snippets.herokuapp.com/tree-folder

![image](https://cloud.githubusercontent.com/assets/8006971/6674432/f6f83930-cbef-11e4-8037-6d9ce88242a6.png)

**Comment by cormacmccarthy** [comment]
This seems to fix it:

```CSS
.fuelux .tree .icon-caret{
    height: 7px;
    box-sizing: border-box;
    width: 1px;
    top: 3px;
    padding-top: 12px;
}
````

http://codepen.io/cormacmccarthy/pen/azQLBm?editors=010

**Comment by mbeard** [comment]
The icon still appears to shift a bit when toggling from closed to open - reducing the top down to 2px seemed to fix it for me.

Also, I noticed that the icon size varies between states.  For example, when closed, the icon is 12x12 but when opened, it's 13x13.  This might need to be a separate issue, but the size should be consistent across states.

**Comment by cormacmccarthy** [comment]
True, that fix will need tweaked to account for open state as well...

**Comment by cormacmccarthy** [comment]
http://codepen.io/cormacmccarthy/pen/azQLBm?editors=010

```CSS
.fuelux .tree .icon-caret, .fuelux .tree .tree-open > .tree-branch-header .icon-caret{
    height: 7px;
    box-sizing: border-box;
    width: 1px;
    top: 3px;
    padding-top: 12px;
}
```
